APP_NAME := airfoil
APP_SRC_EXTRA := airfoil_constants.F90 airfoil_kernels.F90

OP2_LIBS_WITH_HDF5 := true
VARIANT_FILTER_OUT := $(APP_NAME)_mpi_%

include ../../../../makefiles/common.mk
include ../../../../makefiles/f_app.mk
